const uniq = (items) => [...new Set((items || []).map((s) => (s || '').toString().toLowerCase().trim()).filter(Boolean))];

const core = [
  'developer', 'developers', 'software developer', 'software engineer', 'programmer', 'coder',
  'it jobs', 'tech jobs', 'remote jobs', 'freelance', 'freelance jobs', 'contract', 'contract jobs',
  'vacancy', 'vacancies', 'hiring', 'we are hiring', 'looking for developer', 'looking for a developer',
  'need a developer', 'paid task', 'side gig', 'gig', 'startup jobs', 'web3 jobs', 'devops jobs',
  'qa jobs', 'internship', 'junior developer', 'senior developer', 'middle developer',
  // NEW core
  'tech community', 'dev community', 'developer community', 'coding community', 'programmer community',
  'tech group', 'dev group', 'developer group', 'coding group', 'it community', 'it group',
  'tech chat', 'dev chat', 'coding chat', 'developer chat', 'open source', 'open source community',
  'hackathon', 'code review', 'pair programming', 'mentorship', 'tech mentorship', 'dev mentorship',
  'tech news', 'dev news', 'programming news', 'job board', 'tech job board', 'dev job board',
  'remote work', 'remote developer', 'work from home', 'wfh developer', 'async work',
  'entry level', 'mid level', 'senior level', 'lead developer', 'principal engineer', 'staff engineer',
  'tech lead', 'engineering manager', 'cto', 'vp engineering', 'architect',
  'full time', 'part time', 'hourly', 'project based', 'per project', 'fixed price', 'retainer',
  'upwork', 'fiverr', 'toptal', 'turing', 'arc dev', 'gun.io', 'crossover',
  'bootcamp', 'coding bootcamp', 'dev bootcamp', 'self taught', 'cs degree', 'computer science',
  'portfolio', 'github', 'open to work', 'available for hire', 'hire me', 'looking for work',
  'looking for job', 'job seeker', 'job hunt', 'interview prep', 'leetcode', 'system design',
  'technical interview', 'coding interview', 'offer letter', 'salary negotiation', 'equity',
  'developer salary', 'tech salary', 'compensation', 'remote salary', 'dollar salary',
];

const tech = [
  'frontend', 'backend', 'fullstack', 'web', 'mobile', 'android', 'ios',
  'react', 'reactjs', 'react native', 'nextjs', 'vue', 'vuejs', 'nuxt', 'svelte', 'angular',
  'typescript', 'javascript', 'node', 'nodejs', 'express', 'nestjs', 'graphql', 'rest api',
  'python', 'django', 'fastapi', 'flask',
  'java', 'spring', 'kotlin', 'swift',
  'php', 'laravel', 'symfony', 'wordpress', 'shopify',
  'golang', 'go developer', 'rust', 'c++', 'c#', 'dotnet', '.net',
  'unity', 'unreal', 'game dev',
  'qa', 'tester', 'sdet', 'automation testing', 'selenium', 'cypress', 'playwright',
  'devops', 'sre', 'docker', 'kubernetes', 'terraform', 'aws', 'gcp', 'azure', 'linux',
  'postgresql', 'mysql', 'mongodb', 'redis', 'firebase', 'supabase', 'microservices',
  'ai', 'ml', 'machine learning', 'data engineer', 'data scientist', 'nlp', 'computer vision',
  'blockchain', 'web3', 'solidity', 'ethereum', 'ton', 'telegram bot', 'telegraf', 'gramjs',
  // NEW tech
  'astro', 'remix', 'qwik', 'solidjs', 'htmx', 'alpinejs', 'stimulus', 'lit',
  'tailwind', 'tailwindcss', 'css', 'sass', 'scss', 'styled components', 'chakra ui', 'shadcn',
  'redux', 'zustand', 'jotai', 'recoil', 'mobx', 'tanstack query', 'swr',
  'vite', 'webpack', 'esbuild', 'turbopack', 'rollup', 'parcel',
  'bun', 'deno', 'hono', 'elysia', 'fastify',
  'prisma', 'drizzle', 'typeorm', 'sequelize', 'mongoose',
  'trpc', 'grpc', 'websocket', 'socket.io', 'sse', 'webhooks',
  'pwa', 'wasm', 'webassembly',
  'ruby', 'rails', 'ruby on rails',
  'elixir', 'phoenix', 'erlang',
  'scala', 'clojure', 'haskell', 'ocaml', 'f#',
  'perl', 'lua', 'dart', 'flutter', 'maui',
  'r', 'julia', 'matlab',
  'bash', 'shell', 'powershell', 'zsh',
  'git', 'github', 'gitlab', 'bitbucket', 'ci cd', 'github actions', 'jenkins', 'circleci',
  'ansible', 'puppet', 'chef', 'vagrant',
  'nginx', 'apache', 'caddy', 'traefik',
  'kafka', 'rabbitmq', 'nats', 'sqs', 'pubsub', 'celery',
  'elasticsearch', 'opensearch', 'solr', 'meilisearch',
  'sqlite', 'cassandra', 'dynamodb', 'cockroachdb', 'planetscale', 'neon', 'turso',
  'clickhouse', 'bigquery', 'snowflake', 'dbt', 'airflow', 'spark', 'hadoop',
  'grafana', 'prometheus', 'datadog', 'sentry', 'newrelic', 'opentelemetry',
  'cloudflare', 'cloudflare workers', 'vercel', 'netlify', 'railway', 'render', 'fly.io',
  'lambda', 'serverless', 'edge computing',
  'security', 'cybersecurity', 'appsec', 'devsecops', 'penetration testing', 'ethical hacking',
  'oauth', 'jwt', 'auth', 'iam', 'sso', 'keycloak',
  'api design', 'openapi', 'swagger', 'postman', 'insomnia',
  'figma', 'ui ux', 'ux design', 'product design', 'design system',
  'llm', 'gpt', 'openai', 'langchain', 'llamaindex', 'rag', 'vector database', 'embeddings',
  'hugging face', 'transformers', 'pytorch', 'tensorflow', 'keras', 'scikit learn',
  'stable diffusion', 'diffusion models', 'generative ai', 'prompt engineering',
  'defi', 'nft', 'smart contract', 'hardhat', 'foundry', 'wagmi', 'ethers.js', 'web3.js',
  'solana', 'polkadot', 'cosmos', 'near', 'aptos', 'sui', 'avalanche',
  'ton developer', 'twa', 'telegram mini app', 'telegram web app',
  'ios developer', 'android developer', 'react native developer', 'flutter developer',
  'expo', 'capacitor', 'ionic',
  'electron', 'tauri', 'desktop app',
  'embedded', 'iot', 'firmware', 'rtos', 'arduino', 'raspberry pi', 'esp32',
  'computer vision', 'opencv', 'yolo', 'mediapipe',
  'data analysis', 'pandas', 'numpy', 'matplotlib', 'seaborn', 'plotly',
  'tableau', 'power bi', 'looker', 'metabase',
];

const geo = [
  'nigeria developer', 'lagos developer', 'ghana developer', 'kenya developer',
  'uganda developer', 'south africa developer', 'egypt developer',
  'india developer', 'pakistan developer', 'bangladesh developer',
  'philippines developer', 'indonesia developer', 'ukraine developer',
  'poland developer', 'germany developer', 'uk developer', 'canada developer',
  'usa developer', 'mexico developer', 'brazil developer', 'colombia developer', 'latam developer',
  // NEW geo
  'ethiopia developer', 'tanzania developer', 'rwanda developer', 'cameroon developer',
  'senegal developer', 'ivory coast developer', 'zimbabwe developer', 'zambia developer',
  'botswana developer', 'namibia developer', 'mozambique developer', 'malawi developer',
  'sierra leone developer', 'liberia developer', 'gambia developer',
  'morocco developer', 'algeria developer', 'tunisia developer', 'libya developer',
  'sri lanka developer', 'nepal developer', 'myanmar developer', 'vietnam developer',
  'thailand developer', 'malaysia developer', 'singapore developer',
  'cambodia developer', 'laos developer', 'taiwan developer', 'south korea developer',
  'japan developer', 'china developer',
  'russia developer', 'belarus developer', 'georgia developer', 'armenia developer',
  'moldova developer', 'romania developer', 'bulgaria developer', 'serbia developer',
  'croatia developer', 'czech developer', 'slovakia developer', 'hungary developer',
  'greece developer', 'turkey developer', 'israel developer', 'jordan developer',
  'iran developer', 'iraq developer', 'saudi developer', 'uae developer', 'qatar developer',
  'kuwait developer', 'bahrain developer',
  'france developer', 'spain developer', 'italy developer', 'netherlands developer',
  'belgium developer', 'sweden developer', 'norway developer', 'denmark developer',
  'finland developer', 'switzerland developer', 'austria developer', 'portugal developer',
  'argentina developer', 'chile developer', 'peru developer', 'venezuela developer',
  'ecuador developer', 'bolivia developer', 'uruguay developer', 'paraguay developer',
  'costa rica developer', 'panama developer', 'dominican republic developer',
  'australia developer', 'new zealand developer',
  // city-level
  'abuja developer', 'accra developer', 'nairobi developer', 'kampala developer',
  'cairo developer', 'johannesburg developer', 'cape town developer',
  'mumbai developer', 'bangalore developer', 'delhi developer', 'hyderabad developer',
  'karachi developer', 'lahore developer', 'dhaka developer',
  'manila developer', 'jakarta developer', 'kyiv developer', 'warsaw developer', 'berlin developer',
  'london developer', 'toronto developer', 'san francisco developer', 'new york developer',
  'dubai developer', 'istanbul developer', 'moscow developer',
  // community variants
  'african developer', 'african tech', 'west african developer', 'east african developer',
  'south asian developer', 'southeast asian developer', 'eastern european developer',
  'latin american developer', 'middle east developer', 'mena developer',
  'diaspora developer', 'tech diaspora', 'nigerian developer abroad', 'indian developer abroad',
];

// Telegram-community-specific keywords
const tgCommunity = [
  // Group types
  'telegram dev group', 'telegram developer group', 'telegram tech group', 'telegram coding group',
  'telegram programming group', 'telegram it group', 'telegram software group',
  'telegram job group', 'telegram jobs channel', 'telegram vacancy channel',
  'telegram hiring channel', 'telegram freelance group', 'telegram remote jobs',
  'telegram internship group', 'telegram tech community', 'telegram developer community',
  'tg dev group', 'tg tech group', 'tg jobs channel', 'tg community',
  // Tutorial / learning groups
  'telegram tutorial group', 'telegram coding tutorial', 'telegram programming tutorial',
  'telegram python tutorial', 'telegram javascript tutorial', 'telegram web dev tutorial',
  'telegram react tutorial', 'telegram node tutorial', 'telegram django tutorial',
  'telegram flutter tutorial', 'telegram kotlin tutorial', 'telegram swift tutorial',
  'telegram golang tutorial', 'telegram rust tutorial', 'telegram blockchain tutorial',
  'telegram ai tutorial', 'telegram ml tutorial', 'telegram data science tutorial',
  'telegram devops tutorial', 'telegram docker tutorial', 'telegram kubernetes tutorial',
  'telegram linux tutorial', 'telegram git tutorial', 'telegram sql tutorial',
  'telegram leetcode group', 'telegram dsa group', 'telegram algorithm group',
  'telegram system design group', 'telegram interview prep group',
  'telegram bootcamp group', 'telegram study group', 'telegram code review group',
  'telegram open source group', 'telegram hackathon group',
  // Bot / automation community
  'telegram bot developer', 'telegram bot group', 'telegram bot community',
  'tg bot dev', 'telegram bot tutorial', 'telegram automation group',
  'telegram bot jobs', 'telegram bot hiring', 'telegram web app group',
  'ton dev group', 'ton developer community', 'ton blockchain group',
  'telegram mini app developer', 'twa developer', 'telegram games developer',
  // Niche communities
  'python community telegram', 'javascript community telegram', 'react community telegram',
  'node community telegram', 'vue community telegram', 'angular community telegram',
  'flutter community telegram', 'kotlin community telegram', 'swift community telegram',
  'golang community telegram', 'rust community telegram', 'java community telegram',
  'php community telegram', 'laravel community telegram', 'django community telegram',
  'ruby community telegram', 'elixir community telegram', 'scala community telegram',
  'blockchain community telegram', 'web3 community telegram', 'defi community telegram',
  'ai community telegram', 'ml community telegram', 'data science community telegram',
  'devops community telegram', 'sre community telegram', 'cloud community telegram',
  'security community telegram', 'ctf telegram group', 'bug bounty telegram',
  'android community telegram', 'ios community telegram', 'game dev community telegram',
  'embedded community telegram', 'iot community telegram',
  // Role-specific
  'frontend developer group', 'backend developer group', 'fullstack developer group',
  'mobile developer group', 'devops engineer group', 'data engineer group',
  'data scientist group', 'ml engineer group', 'ai engineer group',
  'qa engineer group', 'security engineer group', 'cloud engineer group',
  'ui ux designer group', 'product manager group', 'scrum master group',
  'technical writer group', 'developer advocate group',
  // Job-specific telegram
  'telegram jobs', 'jobs telegram', 'tech jobs telegram', 'it jobs telegram',
  'remote jobs telegram', 'freelance jobs telegram', 'vacancy telegram',
  'hiring telegram', 'developer jobs telegram', 'software jobs telegram',
  'frontend jobs telegram', 'backend jobs telegram', 'fullstack jobs telegram',
  'mobile jobs telegram', 'devops jobs telegram', 'data jobs telegram',
  'ai jobs telegram', 'blockchain jobs telegram', 'web3 jobs telegram',
  'qa jobs telegram', 'security jobs telegram', 'internship telegram',
  'junior jobs telegram', 'senior jobs telegram', 'remote work telegram',
  // geo + telegram
  'nigeria tech telegram', 'lagos tech telegram', 'ghana tech telegram',
  'kenya tech telegram', 'south africa tech telegram', 'india tech telegram',
  'pakistan tech telegram', 'philippines tech telegram', 'indonesia tech telegram',
  'ukraine tech telegram', 'russia tech telegram', 'brazil tech telegram',
  'latam tech telegram', 'mena tech telegram', 'african tech telegram',
];

// Additional role/title keywords
const roles = [
  'solutions architect', 'cloud architect', 'data architect', 'enterprise architect',
  'platform engineer', 'infrastructure engineer', 'network engineer', 'database administrator',
  'dba', 'system administrator', 'sysadmin', 'it support', 'help desk',
  'product manager', 'product owner', 'scrum master', 'agile coach',
  'technical writer', 'technical writer jobs', 'documentation engineer',
  'developer advocate', 'devrel', 'developer relations',
  'growth engineer', 'seo developer', 'analytics engineer',
  'release engineer', 'build engineer', 'tooling engineer',
  'embedded engineer', 'firmware engineer', 'hardware engineer',
  'robotics engineer', 'computer vision engineer', 'nlp engineer',
  'ml ops', 'mlops engineer', 'ai engineer', 'llm engineer',
  'prompt engineer', 'ai researcher', 'research engineer',
  'quant developer', 'fintech developer', 'blockchain engineer',
  'smart contract developer', 'solidity developer', 'web3 developer',
  'dapp developer', 'defi developer', 'protocol engineer',
  'game developer', 'game engineer', 'graphics programmer', 'shader developer',
  'vr developer', 'ar developer', 'xr developer',
  'shopify developer', 'wordpress developer', 'woocommerce developer',
  'magento developer', 'salesforce developer', 'sap developer',
  'oracle developer', 'dynamics developer',
  'low code developer', 'no code developer', 'bubble developer', 'webflow developer',
  'airtable developer', 'zapier developer', 'make developer',
  'api developer', 'sdk developer', 'library developer', 'framework developer',
  'plugin developer', 'extension developer', 'integration developer',
  'test engineer', 'qa automation engineer', 'performance engineer', 'load tester',
  'security researcher', 'penetration tester', 'bug bounty hunter',
  'reverse engineer', 'malware analyst',
  'bi developer', 'etl developer', 'data warehouse engineer',
  'tableau developer', 'power bi developer', 'looker developer',
];

// Learning/tutorial resource keywords
const learning = [
  'coding tutorial', 'programming tutorial', 'web dev tutorial', 'dev tutorial',
  'learn to code', 'learn programming', 'learn javascript', 'learn python',
  'learn react', 'learn nodejs', 'learn golang', 'learn rust', 'learn flutter',
  'learn java', 'learn kotlin', 'learn swift', 'learn typescript', 'learn django',
  'learn fastapi', 'learn docker', 'learn kubernetes', 'learn aws', 'learn devops',
  'learn sql', 'learn nosql', 'learn graphql', 'learn api', 'learn git',
  'learn blockchain', 'learn solidity', 'learn web3', 'learn ai', 'learn ml',
  'coding resources', 'programming resources', 'dev resources', 'tech resources',
  'free courses', 'free programming courses', 'free coding courses',
  'udemy', 'coursera', 'edx', 'pluralsight', 'frontend masters', 'egghead',
  'roadmap', 'dev roadmap', 'developer roadmap', 'learning path', 'curriculum',
  'project ideas', 'portfolio project', 'side project', 'coding project',
  'code challenge', 'coding challenge', 'algorithm challenge', 'hackerrank', 'codeforces',
  'competitive programming', 'dsa', 'data structures', 'algorithms',
  'design patterns', 'clean code', 'solid principles', 'software architecture',
  'api tutorial', 'rest tutorial', 'graphql tutorial', 'microservices tutorial',
  'docker tutorial', 'ci cd tutorial', 'git tutorial', 'linux tutorial',
];

const generated = [];
for (const t of tech) {
  generated.push(
    `${t} developer`,
    `${t} engineer`,
    `${t} jobs`,
    `${t} remote`,
    `${t} freelance`,
    `${t} hiring`,
    `${t} vacancy`,
    `${t} group`,
    `${t} community`,
    `${t} tutorial`,
    `${t} channel`,
    `${t} forum`,
    `${t} chat`,
  );
}

for (const g of geo) {
  generated.push(
    `${g} group`,
    `${g} community`,
    `${g} jobs`,
    `${g} hiring`,
    `${g} channel`,
    `${g} chat`,
    `${g} freelance`,
    `${g} remote`,
  );
}

export const SEED_KEYWORDS = uniq([
  ...core,
  ...tech,
  ...geo,
  ...tgCommunity,
  ...roles,
  ...learning,
  ...generated,
]);