export const SEED_KEYWORDS = [
  'developer',
  'frontend developer',
  'backend developer',
  'fullstack developer',
  'mobile developer',
  'web developer',
  'software engineer',
  'react developer',
  'node developer',
  'python developer',
  'django developer',
  'laravel developer',
  'flutter developer',
  'ios developer',
  'android developer',
  'need a developer',
  'hiring developer',
  'we are hiring',
  'looking for a developer',
  'looking for a programmer',
  'contract developer',
  'freelance developer',
  'paid task',
];
